# Generated by Django 5.0.6 on 2024-05-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('available_space', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_restrictions', models.CharField(max_length=100)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.coordinates')),
            ],
        ),
    ]
