# Generated by Django 5.0.6 on 2024-05-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coordinates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.coordinates'),
        ),
    ]
